version: '2'
services:
  db:
    build: ./db
    container_name: oauth-db
    volumes:
      - ./volumes/mm-ldap/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DB_HOST=oauth-db
      - DB_PORT=5432
      - DB_NAME=oauth_db
      - DB_USER=oauth
      - DB_PASS=oauth_secure-pass
      - CLIENT_ID=client_id
      - CLIENT_SECRET=client_secret
      - REDIRECT_URI=http://mattermost.company.com:8065/signup/gitlab/complete
    restart: always
  app:
    build: ./app
    container_name: oauth-app
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DB_HOST=oauth-db
      - DB_PORT=5432
      - DB_NAME=oauth_db
      - DB_USER=oauth
      - DB_PASS=oauth_secure-pass
      - LDAP_HOST=ldap.company.com
      - LDAP_PORT=389
      - LDAP_BIND_DN
      - LDAP_PASS
      - LDAP_BASE_DN=ou=People,o=Company
      - LDAP_FILTER
      - LDAP_SEARCH_ATTR=uid
      - LDAP_MAIL_ATTR=mail
      - LDAP_NAME_ATTR=cn
      - LDAP_USERNAME_ATTR=name
    ports:
      - "80:80"
    links:
      - db
    restart: always
